#!/bin/bash

echo "======================================="
echo "Railway Environment Variables Setup"
echo "======================================="
echo ""
echo "Copy and paste these into Railway Variables tab:"
echo ""
echo "DATABASE_URL:"
echo "postgresql://postgres:DUFcGYjXaUJaKgIsGzJshauwLZFCtyiS@centerbeam.proxy.rlwy.net:41290/railway"
echo ""
echo "JWT_SECRET:"
echo "WMOMHDuawUdbAm074Zw52UFF26XhchQalz48NhXY7/g="
echo ""
echo "NODE_ENV:"
echo "production"
echo ""
echo "PORT:"
echo "\${PORT}"
echo ""
echo "======================================="
echo "After adding these, your app will redeploy automatically"
echo "======================================="