
import { Student, Task, AgencySettings } from '../types';

/**
 * Simulates sending an email via SMTP (e.g., SendGrid/Resend)
 * Returns a promise that resolves after a realistic network delay.
 */
export const simulateSendEmail = async (
  to: string, 
  subject: string, 
  body: string
): Promise<{ success: boolean; message: string }> => {
  console.log(`[SMTP MOCK] Sending to: ${to}`);
  console.log(`[SMTP MOCK] Subject: ${subject}`);
  console.log(`[SMTP MOCK] Body: ${body}`);
  
  // Simulate network delay
  await new Promise(resolve => setTimeout(resolve, 2000));
  
  return { success: true, message: 'Email queued successfully.' };
};

/**
 * Generates a WhatsApp Click-to-Chat URL
 */
export const generateWhatsAppLink = (phone: string, text: string): string => {
  // Remove non-digit chars, assume country code if missing (defaulting to Nepal +977 for this context or use raw)
  const cleanPhone = phone.replace(/\D/g, '');
  const formattedPhone = cleanPhone.length <= 10 ? `977${cleanPhone}` : cleanPhone;
  
  return `https://wa.me/${formattedPhone}?text=${encodeURIComponent(text)}`;
};

/**
 * Generates a Google Calendar Event Link
 */
export const generateGoogleCalendarLink = (task: Task): string => {
  const daysMap: {[key: string]: number} = {
    'Sunday': 0, 'Monday': 1, 'Tuesday': 2, 'Wednesday': 3, 'Thursday': 4, 'Friday': 5, 'Saturday': 6
  };

  const targetDay = daysMap[task.day] ?? 1;
  const today = new Date();
  const currentDay = today.getDay();
  
  // Calculate days until next occurrence
  let daysUntil = targetDay - currentDay;
  if (daysUntil < 0) daysUntil += 7; // If day passed this week, schedule for next week
  if (daysUntil === 0 && today.getHours() > parseInt(task.dueTime.split(':')[0] || '0')) daysUntil += 7; // If today but time passed

  const targetDate = new Date(today);
  targetDate.setDate(today.getDate() + daysUntil);
  
  // Parse Time
  const [hours, minutes] = task.dueTime.split(':').map(Number);
  targetDate.setHours(hours || 9, minutes || 0, 0, 0);

  const endDate = new Date(targetDate);
  endDate.setHours(targetDate.getHours() + 1); // 1 hour duration default

  // Format dates to YYYYMMDDTHHMMSSZ
  const formatGCalDate = (date: Date) => {
    return date.toISOString().replace(/-|:|\.\d\d\d/g, "");
  };

  const start = formatGCalDate(targetDate);
  const end = formatGCalDate(endDate);

  const title = encodeURIComponent(task.text);
  const details = encodeURIComponent(`Priority: ${task.priority}\nGenerated by StudyAbroad Genius`);

  return `https://calendar.google.com/calendar/render?action=TEMPLATE&text=${title}&details=${details}&dates=${start}/${end}`;
};

/**
 * Processes template strings with variables
 */
export const fillTemplate = (template: string, student: Student, agency: AgencySettings): string => {
    return template
        .replace(/{student_name}/g, student.name)
        .replace(/{country}/g, student.targetCountry)
        .replace(/{status}/g, student.status)
        .replace(/{agency_name}/g, agency.agencyName);
};
